services:
  labcirs_server:
    init: true
    build:
      context: .
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn labcirs.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    restart: &restart-policy always
    volumes:
      - type: bind
        source: ${LABCIRS_MEDIA_DIR:-../media}
        target: /media
      - staticfiles:/static
      - ./labcirs/settings/local_config.json:/app/labcirs/settings/local_config.json

    healthcheck:
      test: "curl --fail -o /dev/null http://localhost:8000/ || exit 1"
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

      
# nginx
  proxy:
    init: true
    image: nginx:stable-alpine-slim
    restart: *restart-policy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/staticfiles
      - type: bind
        source: ${LABCIRS_MEDIA_DIR:-../media}
        target: /mediafiles
    ports:
      - target: 80
        published: ${LABCIRS_PROXY_PORT:-8080}
        protocol: tcp
        mode: host
    depends_on:
      labcirs_server:
        condition: service_healthy

volumes:
  staticfiles:
