# Generated by Django 4.2.20 on 2025-04-12 15:32

import cirs.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    replaces = [('cirs', '0001_initial'), ('cirs', '0002_criticalincident_comment_code'), ('cirs', '0003_comment'), ('cirs', '0004_auto_20180628_1403'), ('cirs', '0005_department_and_roles'), ('cirs', '0006_data_migration_assign_roles_and_create_department'), ('cirs', '0007_add_department_to_models'), ('cirs', '0008_add_translation_model'), ('cirs', '0009_migrate_translatable_fields'), ('cirs', '0010_remove_untranslated_fields'), ('cirs', '0011_add_translation_config_model'), ('cirs', '0012_migrate_translatable_config_fields'), ('cirs', '0013_remove_untranslated_config_fields'), ('cirs', '0014_labcirsconfig_mandatory_languages'), ('cirs', '0015_auto_20190108_1704'), ('cirs', '0016_add_user_change_permission_to_existing_reviewers'), ('cirs', '0017_add_active_field_to_department'), ('cirs', '0018_auto_change_id_to_big_auto_field'), ('cirs', '0019_auto_20240320_2007')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of incident')),
                ('incident', models.TextField(verbose_name='Mistake / problem / critical incident')),
                ('reason', models.TextField(verbose_name='Cause of failure')),
                ('immediate_action', models.TextField(help_text='Immediate action or suggestion regarding prevention / troubleshooting', verbose_name='Immediate action / suggestion')),
                ('preventability', models.CharField(choices=[('indistinct', 'appraisal not possible'), ('avoidable', 'The incident was avoidable'), ('not avoidable', 'The incident was not avoidable')], help_text='In your opinion, was the incident avoidable or not?', max_length=255, verbose_name='Preventability')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Photo')),
                ('public', models.BooleanField(choices=[(True, 'I agree that this report will be made public to people outside the quality management team after copyedit.'), (False, 'I DO NOT agree that this report will be made public to people outside the quality management team even after copyedit.')], default=None, verbose_name='Publication')),
                ('comment_code', models.CharField(blank=True, max_length=16)),
                ('reported', models.DateField(default=datetime.date.today, verbose_name='Date of report')),
                ('action', models.TextField(blank=True, verbose_name='Action')),
                ('responsibilty', models.CharField(blank=True, max_length=255, verbose_name='Responsibility')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Review date')),
                ('status', models.CharField(choices=[('new', 'new'), ('in process', 'in process'), ('under supervision', 'under supervision'), ('completed', 'completed')], default='new', max_length=255, verbose_name='Status')),
                ('risk', models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=255, verbose_name='Risk classification')),
                ('frequency', models.CharField(blank=True, choices=[('singular case', 'singular case (for the first time)'), ('seldom', 'seldom (once per year)'), ('occasional', 'occasional (once per month)'), ('frequent', 'frequent (once per Week)'), ('regular', 'regular (daily)')], max_length=255, verbose_name='Frequency')),
                ('hazard', models.CharField(blank=True, choices=[('very low', 'very low'), ('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('very high', 'very high')], help_text='For emploees or science', max_length=255, verbose_name='Hazard')),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('organisation/communication', 'organisation/communication'), ('technique/methods', 'technique/methods'), ('knowledge/training', 'knowledge/training'), ('concentration/attention (mistake/slip)', 'concentration/attention (mistake/slip)'), ('infrastructure', 'infrastructure'), ('other', 'other')], max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Critical incident',
                'verbose_name_plural': 'Critical incidents',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(help_text='Label can only consist of letters, numbers, underscores and hyphens.', max_length=32, unique=True, verbose_name='Label')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(help_text='Incidents can be created only if department is active.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='LabCIRSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_languages', multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English')], default=['en'], help_text="If you choose mandatory languages besides the default one, don't forget to translate fields below. Further fields in publishable incidents have to be translated before publishing!", max_length=255, verbose_name='Mandatory languages')),
                ('login_info_url', models.URLField(blank=True, verbose_name='URL for login info')),
                ('send_notification', models.BooleanField(default=False, help_text='Check if you wish to be informed about new incidents per email.<br>\n            IMPORTANT: Sender email has to exist and at least one recipient is necessary.<br>\n            BUG: If you had no recipients selected before changingn this setting,\n            please choose at least one and save.<br>\n            Not till then you can activate sending of notifications.', verbose_name='Send notification')),
                ('notification_sender_email', models.EmailField(blank=True, help_text='Enter a valid email address you want to use as a sender', max_length=254, verbose_name='Notification sender email address')),
                ('notification_text', models.TextField(blank=True, help_text='Enter the message which will be send to the reviewer(s) when a new incident is reported', verbose_name='Notification text')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cirs.department', verbose_name='Department')),
                ('notification_recipients', models.ManyToManyField(blank=True, help_text='Choose recipients of the notification email', null=True, to=settings.AUTH_USER_MODEL, verbose_name='Notification recipients')),
            ],
            options={
                'verbose_name': 'LabCIRS configuration',
                'verbose_name_plural': 'LabCIRS configuration',
            },
            bases=(cirs.models.TranslationStatusMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublishableIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
                ('critical_incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cirs.criticalincident', verbose_name='Critical incident')),
            ],
            options={
                'verbose_name': 'Publishable incident',
                'verbose_name_plural': 'Publishable incidents',
                'ordering': ['-id'],
            },
            bases=(cirs.models.TranslationStatusMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='User assigned to other roles and superusers are not listed here!', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reviewer',
                'verbose_name_plural': 'Reviewers',
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='User assigned to other roles and superusers are not listed here!', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reporter',
                'verbose_name_plural': 'Reporters',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='reporter',
            field=models.OneToOneField(help_text='Reporters assigned to other departments are not listed here!', on_delete=django.db.models.deletion.PROTECT, to='cirs.reporter', verbose_name='Reporter'),
        ),
        migrations.AddField(
            model_name='department',
            name='reviewers',
            field=models.ManyToManyField(related_name='departments', to='cirs.reviewer', verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='criticalincident',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cirs.department', verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='Created at')),
                ('text', models.TextField(verbose_name='Text')),
                ('status', models.CharField(choices=[('open', 'open'), ('in process', 'in process'), ('closed', 'closed')], default='open', help_text='Status of the comment', max_length=255, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('critical_incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='cirs.criticalincident', verbose_name='Critical incident')),
            ],
        ),
        migrations.CreateModel(
            name='PublishableIncidentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('incident', models.CharField(max_length=255, verbose_name='Incident')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('measures_and_consequences', models.TextField(blank=True, verbose_name='Measures and consequences')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cirs.publishableincident')),
            ],
            options={
                'verbose_name': 'Publishable incident Translation',
                'db_table': 'cirs_publishableincident_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LabCIRSConfigTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('login_info', models.TextField(help_text='Translate if there are multiple mandatory languages', verbose_name='Login info')),
                ('login_info_link_text', models.CharField(blank=True, help_text='Translate if there are multiple mandatory languages and you store infos at given URL', max_length=255, verbose_name='Link text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cirs.labcirsconfig')),
            ],
            options={
                'verbose_name': 'LabCIRS configuration Translation',
                'db_table': 'cirs_labcirsconfig_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
