# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-20 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cirs', '0002_criticalincident_comment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('text', models.TextField(verbose_name='Text')),
                ('status', models.CharField(choices=[('open', 'open'), ('in process', 'in process'), ('closed', 'closed')], default='open', help_text='Status of the comment', max_length=255, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('critical_incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='cirs.CriticalIncident', verbose_name='Critical incident')),
            ],
        ),
    ]
