# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-28 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalincident',
            name='immediate_action',
            field=models.TextField(help_text='Immediate action or suggestion regarding prevention / troubleshooting', verbose_name='Immediate action / suggestion'),
        ),
    ]
