# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0006_data_migration_assign_roles_and_create_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalincident',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cirs.Department'),
            preserve_default=False,
        ),
    ]
