# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0007_add_department_to_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishableIncidentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('incident', models.CharField(max_length=255, verbose_name='Incident')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('measures_and_consequences', models.TextField(blank=True, verbose_name='Measures and consequences')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cirs.PublishableIncident')),
            ],
            options={
                'managed': True,
                'db_table': 'cirs_publishableincident_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'Publishable incident Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='publishableincidenttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
