# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 11:59
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('cirs', 'PublishableIncident')
    MyModelTranslation = apps.get_model('cirs', 'PublishableIncidentTranslation')

    for _object in MyModel.objects.all():
        for code in ('de', 'en'):
            MyModelTranslation.objects.get_or_create(
                master_id=_object.pk,
                language_code=code,
                incident=getattr(_object, 'incident_'+code),
                description=getattr(_object, 'description_'+code),
                measures_and_consequences=getattr(_object, 'measures_and_consequences_'+code)
            )

def backwards_func(apps, schema_editor):
    MyModel = apps.get_model('cirs', 'PublishableIncident')
    MyModelTranslation = apps.get_model('cirs', 'PublishableIncidentTranslation')

    for _object in MyModel.objects.all():
        for code in ('de', 'en'):
            translation = _get_translation(_object, MyModelTranslation, code)
            for field in ('incident', 'description', 'measures_and_consequences'):
                setattr(_object, '_'.join((field, code)), getattr(translation, field))
            _object.save()   # Note this only calls Model.save()

def _get_translation(_object, MyModelTranslation, code):
    translations = MyModelTranslation.objects.filter(master_id=_object.pk)
    try:
        return translations.get(language_code=code)
    except ObjectDoesNotExist:
        return MyModelTranslation()


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0008_add_translation_model'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
