# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0009_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishableincident',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='incident_de',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='incident_en',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='measures_and_consequences_de',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='measures_and_consequences_en',
        ),
    ]
