# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 13:39
from __future__ import unicode_literals

from django.db import migrations
from django.db import models
from django.utils.translation import gettext_lazy as _

class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0009_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishableincident',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='description_en',
        ),
        migrations.AlterField(
            model_name='publishableincident',
            name='incident_de',
            field=models.CharField(_("Incident (in German)"), max_length=255, default=' '),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='incident_de',
        ),
        migrations.AlterField(
            model_name='publishableincident',
            name='incident_en',
            field=models.CharField(_("Incident (in English)"), max_length=255, default=' '),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='incident_en',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='measures_and_consequences_de',
        ),
        migrations.RemoveField(
            model_name='publishableincident',
            name='measures_and_consequences_en',
        ),
    ]
