# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0010_remove_untranslated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCIRSConfigTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('login_info', models.TextField(help_text='Translate if there are multiple mandatory languages', verbose_name='Login info')),
                ('login_info_link_text', models.CharField(blank=True, help_text='Translate if there are multiple mandatory languages and you store infos at given URL', max_length=255, verbose_name='Link text')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cirs.LabCIRSConfig')),
            ],
            options={
                'managed': True,
                'db_table': 'cirs_labcirsconfig_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'LabCIRS configuration Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='labcirsconfigtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
