# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 21:59
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('cirs', 'LabCIRSConfig')
    MyModelTranslation = apps.get_model('cirs', 'LabCIRSConfigTranslation')

    for _object in MyModel.objects.all():
        for code in ('de', 'en'):
            MyModelTranslation.objects.get_or_create(
                master_id=_object.pk,
                language_code=code,
                login_info=getattr(_object, 'login_info_'+code),
                login_info_link_text=getattr(_object, 'login_info_link_text_'+code)
            )

def backwards_func(apps, schema_editor):
    MyModel = apps.get_model('cirs', 'LabCIRSConfig')
    MyModelTranslation = apps.get_model('cirs', 'LabCIRSConfigTranslation')

    for _object in MyModel.objects.all():
        for code in ('de', 'en'):
            translation = _get_translation(_object, MyModelTranslation, code)
            for field in ('login_info', 'login_info_link_text'):
                setattr(_object, '_'.join((field, code)), getattr(translation, field))
            _object.save()   # Note this only calls Model.save()

def _get_translation(_object, MyModelTranslation, code):
    translations = MyModelTranslation.objects.filter(master_id=_object.pk)
    try:
        return translations.get(language_code=code)
    except ObjectDoesNotExist:
        return MyModelTranslation()

class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0011_add_translation_config_model'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
