# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 23:47
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0013_remove_untranslated_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcirsconfig',
            name='mandatory_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('de', 'German'), ('en', 'English')], default='de,en', max_length=255, verbose_name='Mandatory languages'),
        ),
    ]
