# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0014_labcirsconfig_mandatory_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='criticalincident',
            name='reported',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of report'),
        ),
    ]
