# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 13:26
from __future__ import unicode_literals

from django.db import migrations

def add_permission(apps, schema_editor):
    Reviewer = apps.get_model('cirs', 'Reviewer')
    Permission = apps.get_model('auth', 'Permission')
    permission = Permission.objects.get(codename='change_user')

    for reviewer in Reviewer.objects.all():
        reviewer.user.user_permissions.add(permission)


def remove_permission(apps, schema_editor):
    Reviewer = apps.get_model('cirs', 'Reviewer')
    Permission = apps.get_model('auth', 'Permission')
    permission = Permission.objects.get(codename='change_user')

    for reviewer in Reviewer.objects.all():
        reviewer.user.user_permissions.remove(permission)
            

class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0015_auto_20190108_1704'),
    ]

    operations = [
        migrations.RunPython(add_permission, remove_permission),
    ]
