# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0016_add_user_change_permission_to_existing_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True, help_text='Incidents can be created only if department is active.', verbose_name='Active'),
            preserve_default=False,
        ),
    ]
