# Generated by Django 3.2.25 on 2024-03-20 19:07

from django.db import migrations
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0018_auto_change_id_to_big_auto_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcirsconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cirs.labcirsconfig'),
        ),
        migrations.AlterField(
            model_name='publishableincidenttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cirs.publishableincident'),
        ),
    ]
